# pywb config file - Built for running live under Heroku
# ========================================
#

collections:
    live: $live

# idk stuff from the website but tweaked settings. Banner makes it look ugly, wombat doesn't work, and you need rewriting
proxy:
  enable_banner: false
  enable_wombat: false
  enable_content_rewrite: true

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: false

# uncomment and change to set default locale
default_locale: en

# uncomment to set available locales
locales:
  - en
